"""
Converts a raw PatchCore anomaly score into a severity label, using
per-category thresholds calibrated automatically (see
backend/scripts/calibrate_all_categories.py and
docs/calibration_notes_all_categories.md).

Falls back to the original manually-calibrated bottle thresholds
(Phase 8) if a category's automated calibration file/entry is missing —
this preserves exact backward-compatible behavior for bottle specifically,
since those thresholds were reviewed and discussed in detail, not just
generated by formula.
"""

import json
from enum import Enum
from pathlib import Path

from app.core.config import PROJECT_ROOT

THRESHOLDS_PATH = PROJECT_ROOT / "backend" / "app" / "core" / "severity_thresholds.json"

# Original Phase 8 manually-calibrated bottle thresholds — kept as the
# fallback default so bottle's behavior never silently changes even if
# the automated calibration file is regenerated or missing an entry.
BOTTLE_FALLBACK = {
    "none_ceiling": 32.38,
    "minor_ceiling": 42.0,
    "moderate_ceiling": 50.0,
}


class Severity(str, Enum):
    NONE = "none"
    MINOR = "minor"
    MODERATE = "moderate"
    CRITICAL = "critical"


def _load_thresholds() -> dict:
    if THRESHOLDS_PATH.exists():
        with open(THRESHOLDS_PATH) as f:
            return json.load(f)
    return {}


_ALL_THRESHOLDS = _load_thresholds()


def get_thresholds_for_category(category: str) -> dict:
    return _ALL_THRESHOLDS.get(category, BOTTLE_FALLBACK if category == "bottle" else BOTTLE_FALLBACK)


def estimate_severity(anomaly_score: float, category: str = "bottle") -> Severity:
    """
    Args:
        anomaly_score: raw PatchCore image-level anomaly score.
        category: product category, used to select the correct
            calibrated thresholds. Defaults to "bottle" for
            backward compatibility with existing calls.
    """
    t = get_thresholds_for_category(category)

    if anomaly_score <= t["none_ceiling"]:
        return Severity.NONE
    elif anomaly_score <= t["minor_ceiling"]:
        return Severity.MINOR
    elif anomaly_score <= t["moderate_ceiling"]:
        return Severity.MODERATE
    else:
        return Severity.CRITICAL